version: '3.0'
services:
  mangosd:
    image: tek_mangos_mangosd
    build:
      context: .
      dockerfile: ./services/mangosd/Dockerfile
    links:
      - mysql
      - realmd
    volumes:
      - ./data/mangosd/etc:/runtime/etc
      - ./data/mangosd/data:/runtime/data
    ports:
      - 8085:8085
    restart: unless-stopped
  realmd:
    image: tek_mangos_realmd
    build:
      context: .
      dockerfile: ./services/realmd/Dockerfile
    links:
      - mysql
    volumes:
      - ./data/realmd/etc:/runtime/etc
      - ./data/realmd/data:/runtime/data
    ports:
      - 3724:3724
    restart: unless-stopped
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=mangos
    command:
      - --sql-mode=NO_ENGINE_SUBSTITUTION
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: unless-stopped
  initdb:
    image: tek_mangos_builder
    build:
      context: .
      dockerfile: ./services/builder/Dockerfile
    volumes:
      - ./data/builder/etc:/runtime/etc
      - ./data/builder/data:/runtime/data
    links:
      - mysql
    command: "initdb.sh"