version: '3.0'
services:
  mangosd:
    image: steakhouse.sysroot.ovh/mangosd
    build:
      context: .
      dockerfile: ./services/mangosd/Dockerfile
    links:
      - mysql
      - realmd
    volumes:
      - ./data/mangosd/etc:/runtime/etc
      - ./data/mangosd/data/dbc:/runtime/bin/dbc
      - ./data/mangosd/data/maps:/runtime/bin/maps
      - ./data/mangosd/data/mmaps:/runtime/bin/mmaps
      - ./data/mangosd/data/vmaps:/runtime/bin/vmaps
      # - ./data/builder/data/run/bin/mangosd:/runtime/bin/mangosd
    ports:
      - 8085:8085
    restart: unless-stopped
  realmd:
    image: steakhouse.sysroot.ovh/realmd
    build:
      context: .
      dockerfile: ./services/realmd/Dockerfile
    links:
      - mysql
    volumes:
      - ./data/realmd/etc:/runtime/etc
      - ./data/realmd/data:/runtime/data
      # - ./data/builder/data/run/bin/realmd:/runtime/bin/realmd
    ports:
      - 3724:3724
    restart: unless-stopped
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=mangos
    command:
      - --sql-mode=NO_ENGINE_SUBSTITUTION
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: unless-stopped
  web:
    image: steakhouse.sysroot.ovh/web-cmangos
    ports:
      - 8080:8080
  api:
    image: steakhouse.sysroot.ovh/api-cmangos
    ports:
      - 5556:5556
    links:
      - mysql
    depends_on:
      - mysql
    command: sh -c "sleep 20 && ./api-cmangos contrib/config.ini.dist"
  initdb:
    image: steakhouse.sysroot.ovh/builder
    build:
      context: .
      dockerfile: ./services/builder/Dockerfile
    volumes:
      - ./data/builder/etc:/runtime/etc
      - ./data/builder/data:/runtime/data
    links:
      - mysql
    command: "initdb.sh"